[workspace]
members = [
    "config",
    "messaging",
    "network",
    "p2p-vpn",
]
resolver = "3"

[workspace.dependencies]
libp2p = { version = "0.56.0", features = [ "tokio", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux", "quic", "noise",
    "yamux",
    "identify",
    "ping",
    "relay",
    "dcutr",
    "autonat"] }
tokio = { version = "1.46.1", features = ["full"] }
futures = "0.3.31"
tracing-subscriber = "0.3.19"
config = { path = "config" }
messaging = { path = "messaging" }
network = { path = "network" }