[workspace]
members = [
    "config",
    "messaging",
    "network",
    "p2p-vpn",
    "ui",
]
resolver = "3"

[workspace.dependencies]
libp2p = { version = "0.56.0", features = [ "tokio", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux", "quic"] }
tokio = { version = "1.46.1", features = ["full"] }
iced = "0.13.1"
futures = "0.3.31"
tracing-subscriber = "0.3.19"
config = { path = "config" }
messaging = { path = "messaging" }
network = { path = "network" }
ui = { path = "ui" }
