[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
iroh = { workspace = true }
iroh-gossip = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }