[package]
name = "p2p-vpn"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
libp2p = { workspace = true }
futures = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"]  }