[package]
name = "ticket"
version = "0.1.0"
edition = "2024"

[dependencies]
iroh = { workspace = true }
iroh-gossip = { workspace = true }
data-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }